services:
  postgres:
    image: postgres:16
    container_name: niko_postgres
    environment:
      POSTGRES_DB: niko_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - niko_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  niko:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: niko_web
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/niko_dev
      SECRET_KEY_BASE: "DlwmOxs6p4yW0fWKvaWJnm/kyUcaV7kW750x6I4p6Tq+CQO5A3VLjKPxTmWDEK9f"
    ports:
      - "4000:4000"

volumes:
  niko_postgres_data:
